PORT = 6878
ENCODING = "utf-8"
JOIN_CHANNEL_CMD = "JOIN_CHANNEL"
CREATE_CHANNEL_CMD = "CREATE_CHANNEL"
CHANGE_NICKNAME_CMD = "CHANGE_NICKNAME"
DIRECT_MESSAGE_CMD = "DIRECT_MESSAGE"
BUFFER_SIZE = 1024

# removes whitespaces
def format_string(value):
    return value.replace(" ", "")
